runtime: nodejs22

automatic_scaling:
  max_instances: 20

handlers:
  - url: /static
    static_dir: dist/assets

  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|svg|webp|gif|txt))$
    static_files: dist/\1
    upload: dist/(.*)

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
